// <auto-generated />
using HELPS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HELPS.Migrations
{
    [DbContext(typeof(HelpsContext))]
    [Migration("20190527063540_studentWorkshop")]
    partial class studentWorkshop
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HELPS.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HELPS.Models.student_workshops", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("available_places");

                    b.Property<string>("description");

                    b.Property<int>("duration");

                    b.Property<string>("room_id");

                    b.Property<string>("targetGroup");

                    b.Property<string>("time");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("s_workshop");
                });
#pragma warning restore 612, 618
        }
    }
}
