// <auto-generated />
using HELPS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HELPS.Migrations
{
    [DbContext(typeof(HelpsContext))]
    partial class HelpsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HELPS.Models.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Advisors");
                });

            modelBuilder.Entity("HELPS.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HELPS.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BestContactNumber");

                    b.Property<string>("CountryOfOrigin");

                    b.Property<string>("Course");

                    b.Property<string>("DOB");

                    b.Property<string>("Degree");

                    b.Property<string>("EducationalBackground");

                    b.Property<string>("Email");

                    b.Property<string>("Faculty");

                    b.Property<string>("FirstLanguage");

                    b.Property<string>("Gender");

                    b.Property<bool>("HasCompletedCAF");

                    b.Property<string>("HomePhone");

                    b.Property<bool>("IsSpecialNeeds");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("Name");

                    b.Property<string>("Other");

                    b.Property<string>("PrefFirstName");

                    b.Property<string>("RegisteredDate");

                    b.Property<string>("Status");

                    b.Property<string>("Year");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HELPS.Models.student_workshops", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("available_places");

                    b.Property<string>("description");

                    b.Property<int>("duration");

                    b.Property<string>("room_id");

                    b.Property<string>("targetGroup");

                    b.Property<string>("time");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("s_workshop");
                });
#pragma warning restore 612, 618
        }
    }
}
