export enum AuthActionType {
    REQUEST_LOGIN = 'AUTH_ACTION_REQUEST_LOGIN',
    RECEIVE_LOGIN = 'AUTH_ACTION_RECEIVE_LOGIN',

    LOGIN_ERROR = 'AUTH_ACTION_LOGIN_ERROR',
    REQUEST_LOGOUT = 'AUTH_ACTION_REQUEST_LOGOUT',
    RECEIVE_LOGOUT = 'AUTH_ACTION_RECEIVE_LOGOUT',
    LOGOUT_USER = 'AUTH_ACTION_LOGOUT_USER'

    LOGOUT = 'AUTH_ACTION_LOGOUT',
    LOGIN_ERROR = 'AUTH_ACTION_LOGIN_ERROR'

}

export interface AuthAction {
    type: AuthActionType,
    payload?: any
}